src/src/Entity/Offer.php
<?php

namespace App\Entity;

use App\Repository\OfferRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OfferRepository::class)
 */
class Offer
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $offer_id;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=256)
     */
    private $image_url;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=2)
     */
    private $cash_back;

    /**
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $position;

    public function getId(): ?int
    {
        return $this->offer_id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->image_url;
    }

    public function setImageUrl(string $image_url): self
    {
        $this->image_url = $image_url;

        return $this;
    }

    public function getCashBack(): ?float
    {
        return $this->cash_back;
    }

    public function setCashBack(float $cash_back): self
    {
        $this->cash_back = $cash_back;

        return $this;
    }

    public function getPosition(): ?int
    {
        return $this->position;
    }

    public function setPosition(?int $position): self
    {
        $this->position = $position;

        return $this;
    }
}

src/src/Controller/OfferController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Manager\OfferManager;

class OfferController extends AbstractController
{
    private $manager;

    public function __construct(OfferManager $manager)
    {
        $this->manager = $manager;
    }

    #[Route('/offer', name: 'get_offers')]
    public function cgetAction(Request $request): Response
    {
        $sort = $request->query->get('sort') ?? null;
        $direction = $request->query->get('direction') ?? null;
        $output = $request->query->get('output') ?? null;
        $data = $this->manager->getOffers($sort, $direction);

        if ($output === 'json') {
            return $this->json($data);
        }

        return $this->render('offer/index.html.twig', [
            'data' => $data
        ]);
    }

    #[Route('/offer/{offer_id}', name: 'get_offer')]
    public function getAction(Request $request, int $offer_id): Response
    {
        $output = $request->query->get('output') ?? null;
        $data = $this->manager->getOffer($offer_id);

        if (empty($data)) {
            throw $this->createNotFoundException('The offer does not exist');
        }

        if ($output === 'json') {
            return $this->json($data);
        }

        return $this->render('offer/index.html.twig', [
            'data' => [$data]
        ]);
    }
}

src/templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

        {% block javascripts %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

src/templates/offer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Your Offers{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 100%; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1 class="text-center">Your offers</h1>
    <p class="text-end"><a href="{{ path('get_offers', {'sort': 'offer_id', 'direction': 'ASC', 'output': 'json'}) }}">JSON output?</a></p>

    <table class="table table-striped">
        <caption>List of offers</caption>
        <thead class="table-dark">
            <tr>
                <th scope="col"><a class="text-white" href="{{ path('get_offers', {'sort': 'offer_id', 'direction': 'ASC'}) }}">#</a></th>
                <th scope="col"><a class="text-white" href="{{ path('get_offers', {'sort': 'name', 'direction': 'ASC'}) }}">Name</a></th>
                <th scope="col">Image</th>
                <th scope="col"><a class="text-white" href="{{ path('get_offers', {'sort': 'cash_back', 'direction': 'DESC'}) }}">Cash back</a></th>
            </tr>
        </thead>
        <tbody>
        {% for offer in data %}
            <tr>
                <th scope="row"><a href="{{ path('get_offer', {offer_id: offer.id}) }}">{{offer.id}}</a></th>
                <td>{{offer.name}}</td>
                <td><img src="{{offer.imageUrl}}" class="img-thumbnail"></td>
                <td>{{offer.cashBack|format_currency('CAD')}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}